### ISSUE TITLE
Becoming package maintainer

### ISSUE THREAD

**Issue by ghost** [gulpjs/vinyl-contents#4]
It looks like you guys are busy, so maybe I can become a maintainer? It shouldn't be too much trouble, as I really need this package quite often. Let me know what you think!

**Comment by ghost** [comment]
Going to ping @phated as I believe he is the owner of this repository.

**Comment by phated** [comment]
Hey @samvv - while I appreciate your excitement around this package but we only onboard new maintainers to the gulp team after substantial and consistent PRs.
